[pytest]
addopts = -ra -q --maxfail=1 --html=reports/report.html --self-contained-html --alluredir=reports/allure-results
testpaths = tests
python_files = test_*.py
markers =
    smoke: quick smoke tests
    regression: full regression
